### ISSUE TITLE
Sync Website/Readme on Usage

### ISSUE THREAD

**Issue by ioneyed** [boxtown/verto#3]
I was reading over the Readme and then noticed your website (advertised as the repo description) has more example (and a typo) than the readme. Suggestion is to update the content of both to be equal. I am excited to try this framework out and expand my GO knowledge.

The typo in the website is in the "Session" section (https://boxtown.io/#/projects/verto/dev), you missed a two closing double quotes and the side nav doesn't jump to the section on Chrome 52 on Mac OSX El Capitan.

```
    import (
    "github.com/boxtown/verto //Missing quote
    "github.com/boxtown/verto/session //Missing Quote
    "net/http"
    )
```

should be 

```
    import (
    "github.com/boxtown/verto"
    "github.com/boxtown/verto/session"
    "net/http"
    )
```

**Comment by boxtown** [comment]
Thanks for the heads up! I'll look into it

**Comment by boxtown** [comment]
fixed
